# Generated by Django 3.1.7 on 2021-06-12 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='phone',
            field=models.CharField(default=23, max_length=15),
        ),
        migrations.AlterField(
            model_name='members',
            name='position',
            field=models.CharField(default=12, max_length=50),
        ),
    ]
